server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_MAIN_PATH:/api}
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

jstorage:
  root-path: ${ROOT_PATH:.\tmp}
  download-filename: ${DOWNLOAD_FILENAME:jstorage-file}
  service:
    host: ${SERVICE_HOST:http://localhost:${server.port}}${server.servlet.context-path}